### ISSUE TITLE
mount.nfs: access denied by server while mounting 192.168.56...

### ISSUE THREAD

**Issue by jdart** [simonswine/vagrant-hanewin-nfs#1]
Hi Simon,

I'm hoping this plugin is the silver bullet for performance and folder sharing on a windows host. Anywho I'm running windows 8.1, and installed hanewin. I get the below error when doing a vagrant up with folder_sharing type nfs. One thing I noticed, the ip address is incomplete - it should be "192.168.56.101". Other than installing hanewin do I need to do anything else? I was running "vagrant up" from a shell with admin privileges.

==> default: Installing NFS client...
==> default: Exporting NFS shared folders...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp,nolock' 192.168.56.1:'/c/Users/j/project/TeamTalk' /vagrant

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 192.168.56.1:/c/Users/j/project/TeamTalk

**Comment by simonswine** [comment]
Hi Jonathan, 

the following things would help me to debug this issue:
- contents of the file <tt>C:/Program Files/nfsd/exports</tt>.  
- <tt>ifconfig</tt> on the VM
- <tt>ipconfig</tt> on the Host
- <tt>Vagrantfile</tt>, at least the network parts of it.

Cheers,
simon

**Comment by jdart** [comment]
I suspect it's the options 'vers=3,udp,nolock' that are the problem, I will try removing those. If it doesn't help I'll provide more details.

**Comment by jdart** [comment]
So those settings weren't present as I expected.

Exports:

# exports example

C:\ftp -range 192.168.1.1 192.168.1.10
c:\public -public -readonly
c:\tools -readonly 192.168.1.4

C:\Users\j\project\TeamTalk -mapall:1000:1000 192.168.56.101 ##VAGRANT#b656b63b-37ed-4996-a4b7-e5fca9c92c1b#

ifconfig on VM

eth0      Link encap:Ethernet  HWaddr 08:00:27:3a:bc:fc
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe3a:bcfc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2041 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1288 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:583218 (583.2 KB)  TX bytes:159144 (159.1 KB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:1b:db:ec
          inet addr:192.168.56.101  Bcast:192.168.56.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:117 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:9365 (9.3 KB)  TX bytes:978 (978.0 B)

ipconfig on host

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::c110:4ad6:74d3:7ed9%28
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Vagrantfile:

It's generated by puphpet.com and uses a yaml file for configuration. It's probably easiest to head over to the site for a full example.

  if data['vm']['network']['private_network'].to_s != ''
    config.vm.network 'private_network', ip: "#{data['vm']['network']['private_network']}"
  end

The private_network value is "192.168.56.101"

FWIW I tried this afternoon on another windows 8.1 machine with a vaprobash generated vagrantfile and it did work.

**Comment by jdart** [comment]
Some output from the guest os:

$ sudo mount -v -o 'vers=3,udp,nolock' 192.168.56.1:'/c/Users/j/project/TeamTalk' /vagrant2
mount: no type was given - I'll assume nfs because of the colon
mount.nfs: timeout set for Sat Sep 27 03:07:01 2014
mount.nfs: trying text-based options 'vers=3,udp,nolock,addr=192.168.56.1'
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: trying 192.168.56.1 prog 100003 vers 3 prot UDP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 192.168.56.1 prog 100005 vers 3 prot UDP port 1058
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting 192.168.56.1:/c/Users/j/project/TeamTalk

**Comment by simonswine** [comment]
The input you provided contains as far as I can see no mistakes. This steps can be worth trying:
- Ensure that Windows Firewall  (and any other) is switched off
- Try move C:\Users\j\project\TeamTalk to C:\teamtealk and try again

**Comment by jdart** [comment]
Thanks Simon for the follow up, I decided to attempt other options.

**Comment by entr** [comment]
I experienced same results.
